### ISSUE TITLE
possibility to leverage the typings in @esri/arcgis-rest-js?

### ISSUE THREAD

**Issue by jgravois** [Esri/arcgoose#1]
hey @mvdbster :wave:! just saw this very cool project!

i only took a quick snoop through the code, but it got me thinking that it sure would be great if you could reuse all the typings we've been putting together in [`@esri/arcgis-rest-common-types`](https://github.com/Esri/arcgis-rest-js/tree/master/packages/arcgis-rest-common-types). not sure if/how that'd work in a vanilla JS project though...

**Comment by mvdbster** [comment]
@jgravois our next step is to use `[arcgis-rest-js](https://github.com/Esri/arcgis-rest-js)` instead of the JS API `[esri/request](https://developers.arcgis.com/javascript/latest/api-reference/esri-request.html)` 👍

I'm not sure of those common types make sense right now as `arcgoose` is focused on consuming feature services only.
